### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by InfiniteTurbo** [ReckerXF/ts3-queue-bot#1]
I keep getting this error for every command I run:

![image](https://github.com/Blizzard098/ts3-queue-bot/assets/79483260/ea45d28c-c41d-46da-bbbe-e8c4dc4b034c)

**Comment by runyonjake** [comment]
Same... any fixes?

**Comment by ReckerXF** [comment]
Never got the notification for this issue being made.. odd.

I'll take a peek here when I can - I am a bit busy at the moment.

**Comment by xCashz** [comment]
> Never got the notification for this issue being made.. odd.
> 
> I'll take a peek here when I can - I am a bit busy at the moment.

Any update @Blizzard098?

**Comment by ItsNixk0** [comment]
@ReckerXF Having same issue here.

**Comment by ReckerXF** [comment]
Apologies for the huge delay,

I have had a lack of a proper testing environment and have had higher priorities. Now that I have more ample time and an established testing environment, I will be working on this within the next 24 hours.

I already have the redis issues fixed, I am just making some miscellaneous fixes for bugs that I have overlooked but found during my redis debugging. Thanks for all of your patience!

**Comment by ItsNixk0** [comment]
> Apologies for the huge delay,
> 
> I have had a lack of a proper testing environment and have had higher priorities. Now that I have more ample time and an established testing environment, I will be working on this within the next 24 hours.
> 
> I already have the redis issues fixed, I am just making some miscellaneous fixes for bugs that I have overlooked but found during my redis debugging. Thanks for all of your patience!

Thank you for the reply. Hope to get this working soon!

**Comment by ReckerXF** [comment]
Update has been made.
