### ISSUE TITLE
Utils Update

### ISSUE THREAD

**Issue by ItsNixk0** [ReckerXF/ts3-queue-bot#2]
Hello! In the Utils file, lines 49-51

> let currentChannelDesc = (await this._client.channelInfo(this._client._config.botOptions.queueChannelID)).channelDescription || "";
            let currentChannelName = (await this._client.channelInfo(this._client._config.botOptions.queueChannelID)).channelName;
            this._client.channelEdit(queue.channel, {channelName: `${currentChannelName} | Queue: ${(await QueueHandler.getQueue(queue.queueName)).length}`, channelDescription: `[size=10][color=lightblue][b][Queue][/b][/color][/size]\n${mappedQueue}\n${currentChannelDesc}`});

I noticed it changes the channel the users are queing for correctly, however it updates it to the name and description of the Queue Channel ID. 

Updated Lines:
  >  let currentChannelDesc = (await this._client.channelInfo(queue.channel)).channelDescription || "";
            let currentChannelName = (await this._client.channelInfo(queue.channel)).channelName;
            this._client.channelEdit(queue.channel, {channelName: `${currentChannelName} | Queue: ${(await QueueHandler.getQueue(queue.queueName)).length}`, channelDescription: `[size=10][color=lightblue][b][Queue][/b][/color][/size]\n${mappedQueue}\n${currentChannelDesc}`});

**Comment by ReckerXF** [comment]
Pushed the fix, appreciate it!

Feel free to make PRs btw if you'd like :)
